apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: traefik/whoami:latest
        ports:
        - containerPort: 80
        env:
        - name: WHOAMI_NAME
          value: "Hello again, from app3 and Simona."
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - port: 80
      targetPort: 80