Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-13"
    
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024 
    end
    
    config.vm.define "saimarS" do |server|
        server.vm.hostname = "saimarS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "saimarS"
        end

        server.vm.provision "shell", path: "scripts/server.sh"
    end
end