Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.boot_timeout = 600


  # Machine 1.
  config.vm.define "tpandyaS" do |server|
    server.vm.hostname = "tpandyaS"
    server.vm.network "private_network", ip: "192.168.56.110"

  # Hardware and Provider
    server.vm.provider "virtualbox" do |vb|
     vb.name = "tpandyaS" # also for worker machine but will see
     vb.cpus = 1
     vb.memory = 1024 
     # Required for Apple Silicon ARM64 VirtualBox networking:
     vb.customize ["modifyvm", :id, "--nic-type1", "virtio"]
     vb.customize ["modifyvm", :id, "--nic-type2", "virtio"]
    end
  # Script
    server.vm.provision "shell", path: "scripts/setup.sh"
  end

  
  # Machine 2.
  config.vm.define "tpandyaSW" do |agent|
    agent.vm.hostname = "tpandyaSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

  # Hardware and Provider
    agent.vm.provider "virtualbox" do |vb|
     vb.name = "tpandyaSW"
     vb.cpus = 1
     vb.memory = 1024 
     # Required for Apple Silicon ARM64 VirtualBox networking:
     vb.customize ["modifyvm", :id, "--nic-type1", "virtio"]
     vb.customize ["modifyvm", :id, "--nic-type2", "virtio"]
    end
  # Script
    agent.vm.provision "shell", path: "scripts/setupWorker.sh"
  end

 
end
